name: ci
on: [push]
jobs:
  run_ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Build AprilTag
      run: make apriltag

    - name: Install AprilTag
      run: make install_apriltag

    - name: Build AprilTag Python Bindings
      run: make pybind

    - name: Install AprilTag Python Bindings
      run: make install_pybind
